[project]
site_name = "IOC Cleanup"

docs_dir = "docs_"
site_dir = "docs"

nav = [
  {"Home" = "index.md"},
  {"Concept" = "concept.md"},
  {"Reference" = [
    {"JSONs" = "reference/json-schema.md"},
    {"Data Architecture" = "reference/data-layout.md"},
    {"API" = "reference/python-api.md"},
  ]},
  {"Dashboard" = [
    {"Usage" = "workflows/dashboard.md"},
  ]},
  {"Limitations" = "limitations.md"},
  {"Contributing" = "contributing.md"},
]

[project.theme]
features = [
    "navigation.tabs",
    "navigation.path",
    "navigation.top",
    "toc.integrate",
    "content.code.copy"
]

[project.theme.icon]
logo = "material/waves"


# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# admonitions
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

# lists
[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

# emojis
[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]

# code snippets
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.inlinehilite]

# API
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
signature_crossrefs = true
show_source = true
show_signature = true
show_docstring_description= true
show_root_heading= true
show_symbol_type_heading = true
heading_level = 3
